// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWIVWhm2XxPBCQzD8h4I7jF-YSpvUwzzU',
    appId: '1:1067930811785:web:c4aadf9d6b008a58f47558',
    messagingSenderId: '1067930811785',
    projectId: 'eos-clock-23140',
    authDomain: 'eos-clock-23140.firebaseapp.com',
    storageBucket: 'eos-clock-23140.appspot.com',
    measurementId: 'G-1P4VS6ZXGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv9JPQEaEnO0EybCPxEl1qYP6it5htM-U',
    appId: '1:1067930811785:android:45e31f9dfcca575af47558',
    messagingSenderId: '1067930811785',
    projectId: 'eos-clock-23140',
    storageBucket: 'eos-clock-23140.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD5XxZl3MnP4yUrLf7Vb5-Tcj2fFSKmFQ',
    appId: '1:1067930811785:ios:ce31cc65802f2e09f47558',
    messagingSenderId: '1067930811785',
    projectId: 'eos-clock-23140',
    storageBucket: 'eos-clock-23140.appspot.com',
    iosClientId: '1067930811785-cenudjuau6dm6l8ntr3dkee2qks2fdt2.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosClock',
  );
}
