name: eos_clock
description: A new Flutter project.
publish_to: "none" # Do not publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-Regular.ttf